language: python

python:
  - "2.7.12"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - run app.py
script:
  - coverage run test_api.py
  - coverage run test_base.py
  - coverage run test_server.py
