language: python
sudo: true
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python app.py
  - coverage run test_api.py
  -coverage run test_base.py
after_success:
  - codecov
